AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  Enabled: false
  Include:
    - "spec/**/*"

Metrics/BlockLength:
  Enabled: false
  Include:
    - "spec/**/*"
